# Site wide configuration

title:            Cocoamon
locale:           en_US
url:              


# Jekyll configuration
permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-optional-front-matter
  - jekyll-default-layout
  - jekyll-titles-from-headings
  - jekyll-seo-tag

optional_front_matter:
  enabled: true 
  
kramdown:
  auto_ids: true
  syntax_highlighter: rouge
  input: GFM

defaults:
  - scope:
      path: "posts"
      layout: post
    values:
      strip_title: true  

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

#  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  
# Site owner
owner:
  name: Diederik Hoogenboom
  avatar: bio-photo.jpg
  bio: "Mac/iOS Developer at Obvious Matter"
  email: 
  web: "http://obviousmatter.com"
  disqus-shortname: 
  google:
    plus:
    analytics: UA-59324716-1
    verify: 
    ad-client: 
    ad-slot: 
  github: diederikh
  stackoverflow: 118908/diederikh
  linkedin: diederikhoogenboom

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
